### ISSUE TITLE
Could not read xml file in Matrix Generation

### ISSUE THREAD

**Issue by clendara1** [biosemantics/etc-site#107]
During Matrix generation step I chose the input files from a shared folder and received the message that the system was going to copy it in the owned folder. The system then gave the following error shown in the screen shot

![image](https://cloud.githubusercontent.com/assets/8581741/4078651/d540ea86-2ecd-11e4-97ed-c9630d926a98.png)

**Comment by rodenhausen** [comment]
could not be reproduced
