### ISSUE TITLE
corrected typo not corrected in the source file

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#129]
I correct strongylox_eas to strongy_loxeas at term review step, but it still seems to exist in the source:
![image](https://cloud.githubusercontent.com/assets/831423/4939804/831d3798-65d5-11e4-9d3b-26a93a04e217.png)

**Comment by rodenhausen** [comment]
need to correct the typo in all the database tables created by learn step, parse step reads not the input files but sentences and other artifacts from the DB.

**Comment by rodenhausen** [comment]
check if text element is populated from sentence table; if so which column original sentence or sentence

**Comment by rodenhausen** [comment]
singular plural can be problematic

**Comment by rodenhausen** [comment]
use inflector of semanticmarkup package to get plural

**Comment by rodenhausen** [comment]
write changes through to all fields for: taxon name terms
write changes through only to description fields for: description terms
