### ISSUE TITLE
Key Generation: upload input cvs file 

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#145]
also need to describe the format of the cvs file, specifically:
0. row = taxa, colume=character
1. formation of taxon name strings
2. formation of values in characters: 0|1, large|small, etc.
3. are quotations required to separate values?

**Comment by rodenhausen** [comment]
upload works. format needs to be described

**Comment by rodenhausen** [comment]
this config describes the CSV parameters.
https://github.com/biosemantics/etc-site/blob/master/src/main/resources/edu/ucdavis/cs/cfgproject/config.properties.template

in use e.g. here https://github.com/biosemantics/cfgproject/blob/master/src/main/java/edu/ucdavis/cs/cfgproject/server/rpc/KeyGenerationService.java#L27
