### ISSUE TITLE
Key Generation: layout issue after rewind (Chrome)

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#153]
![image](https://cloud.githubusercontent.com/assets/831423/5377854/1dc338ec-8043-11e4-8116-b610347f3d66.png)

**Comment by rodenhausen** [comment]
We decided to change the layout of the character state portion to consist of an AccordionLayoutContainer for "useful, selected and uselss". Then another layer of AccordionLayoutContainers inside these, to hold each character as a contentpanel. Each character's content panel then contains one state on a line with the checkbox. This will allow remove the issue with character width and (unknown number of states) checkboxes floating around. Initially all the characters in the accordion should be expanded. Right click should allow to expand/collapse all to show/hide the states of all.
