### ISSUE TITLE
can not select multiple taxa

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#159]
the video clip that shows this issue is at http://screencast.com/t/FCmsFMki

and http://screencast.com/t/e68ibNFaXa

**Comment by hongcui** [comment]
it was because authority/date are not provided for the taxa in the input files

**Comment by rodenhausen** [comment]
Solution: On input creation/input step, inform user that name, authority, date needs to be unique. List redundant information to fix.

Needs to be addressed in file manager; and also in matrix generation input.
