### ISSUE TITLE
Edit input schema to require taxon_name authority and date

### ISSUE THREAD

**Issue by rodenhausen** [biosemantics/etc-site#161]
A. Edit schema as described
B. Update input creation (batch + single to accomodate for those)

In detail for batch mode, Hong: "1. I will update the instruction and ask the user to include authority and date for the lowest-ranked taxon name. They can omit the info when the author/year can be used as the authority/date for the taxon. If that is not the case, they need to make up some-sort of unique string to file the two slots.
2. In the code, when authority/date info is missing for a taxon, pop up an warning message, and allow the user (a) to process and use author/year info as authority/date or (b) go back and edit their input. 

'taxon name' refers to genus name, species name fields in the instruction (of batch creation) not taxon_identification element (in schema)"

Problem that lead to this issue: Taxon hierarchy can't be built if taxon concepts with same name but different authority/date exist.

**Comment by hongcui** [comment]
done.
