### ISSUE TITLE
matrix review 1 bug and 2 observations

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#162]
Related to matrix review interface
1. bug

http://screencast.com/t/O0URvDOywo. 

2. observations:

a. I can add comments to data cell, but there is no visual clue to show which data cell has a comment, and mouse-over a cell does not show comments either.

b. when a character is controlled, adding invalidate values is not allowed, but it would be nice to popup a message say 'the input value is not valid, because the character only accepts numerical/.../.../..../ values".

**Comment by rodenhausen** [comment]
Can you give complete steps to reproduce the colorization issue shown in
the screencast? Including the input dataset and all required steps.
I can't reproduce the problem on my end at this time.

**Comment by rodenhausen** [comment]
a. A mouse over to a cell with a comment shows me the comment. Can you
again give all required steps to reproduce what you encounter?

b. Adding invalid values does popup a message for me saying that it is
invalid. It shows the message as you type, not after you have have finished
editing by pressing enter. Do you not see that message or did you press
enter to quickly maybe?

**Comment by hongcui** [comment]
I sorted the characters using varied sorting function that may be the cause

On Tue, Jan 6, 2015 at 10:03 AM, rodenhausen <notifications@github.com>
wrote:

> Can you give complete steps to reproduce the colorization issue shown in
> the screencast? Including the input dataset and all required steps.
> I can't reproduce the problem on my end at this time.
>
> On Tue, Jan 6, 2015 at 9:26 AM, hongcui <notifications@github.com> wrote:
>
> > Related to matrix review interface
> > 1. bug
> >
> > http://screencast.com/t/O0URvDOywo.
> >
> > 1. observations:
> >
> > a. I can add comments to data cell, but there is no visual clue to show
> > which data cell has a comment, and mouse-over a cell does not show
> comments
> > either.
> >
> > b. when a character is controlled, adding invalidate values is not
> > allowed, but it would be nice to popup a message say 'the input value is
> > not valid, because the character only accepts numerical/.../.../..../
> > values".
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/biosemantics/etc-site/issues/162>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biosemantics/etc-site/issues/162#issuecomment-68894602>
> .
>



-- 
Hong Cui, Ph.D <http://sirls.arizona.edu/hongcui>
Associate Professor, Information Technology
School of Information Resource and Library Science
<http://sirls.arizona.edu>
University of Arizona

Member of Plazi.org

**Comment by hongcui** [comment]
http://screencast.com/t/X0pYyhlujr

I tried to type my invalid value slowly, but no error message pops up :

http://screencast.com/t/riNQ4v7H9hoF

I used chrom.

Hong

On Tue, Jan 6, 2015 at 10:06 AM, rodenhausen <notifications@github.com>
wrote:

> a. A mouse over to a cell with a comment shows me the comment. Can you
> again give all required steps to reproduce what you encounter?
>
> b. Adding invalid values does popup a message for me saying that it is
> invalid. It shows the message as you type, not after you have have
> finished
> editing by pressing enter. Do you not see that message or did you press
> enter to quickly maybe?
>
> On Tue, Jan 6, 2015 at 10:02 AM, Thomas Rodenhausen <
> thomas.rodenhausen@gmail.com> wrote:
>
> > Can you give complete steps to reproduce the colorization issue shown in
> > the screencast? Including the input dataset and all required steps.
> > I can't reproduce the problem on my end at this time.
> >
> > On Tue, Jan 6, 2015 at 9:26 AM, hongcui <notifications@github.com>
> wrote:
> >
> >> Related to matrix review interface
> >> 1. bug
> >>
> >> http://screencast.com/t/O0URvDOywo.
> >>
> >> 1. observations:
> >>
> >> a. I can add comments to data cell, but there is no visual clue to show
> >> which data cell has a comment, and mouse-over a cell does not show
> comments
> >> either.
> >>
> >> b. when a character is controlled, adding invalidate values is not
> >> allowed, but it would be nice to popup a message say 'the input value
> is
> >> not valid, because the character only accepts numerical/.../.../..../
> >> values".
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/biosemantics/etc-site/issues/162>.
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biosemantics/etc-site/issues/162#issuecomment-68895198>
> .
>



-- 
Hong Cui, Ph.D <http://sirls.arizona.edu/hongcui>
Associate Professor, Information Technology
School of Information Resource and Library Science
<http://sirls.arizona.edu>
University of Arizona

Member of Plazi.org

**Comment by rodenhausen** [comment]
TODO: 
- visual clue of comment
- input validation on categorical states while typing
