### ISSUE TITLE
Email notification instruction

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#222]
We need to update the instruction about email notification cross the site, since the user could disable email notification. I suggest the text to be changed to something like : 

"You will be notified by an email when the process is complete, if you didn't disable email notification function on your account (Link to Account page), otherwise, 
you can check the status of the task at anytime via the Task Manager (Link to Task Manager)"

![image](https://cloud.githubusercontent.com/assets/831423/6791988/db576080-d170-11e4-810d-db2d9c202038.png)

**Comment by sanketajoshi** [comment]
Earlier messages replaced by following message 
"If you didn't disable email notification, you will receive an email when the process is complete"
