### ISSUE TITLE
Remove a line from File Manager Instruction

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#234]
remove the last line in the instruction below:
![image](https://cloud.githubusercontent.com/assets/831423/7034878/96a6a706-dd38-11e4-9d39-19d7ee1a3ba2.png)

copy the remaining text as instructions for File Manager.

**Comment by sanketajoshi** [comment]
Modified last line  in instructions of  file manager
" To start a tool, mouse over the menu icon at left top corner of the page to expand it, then select the tool there, or, go to Home, then select a tool."
