### ISSUE TITLE
on close, File Manager starts 'loading' process

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#250]
see
http://screencast.com/t/ekDdl87BrbB

When one have many files in the file manager, this loading process is quite long.

**Comment by rodenhausen** [comment]
It didn't start on close. It started upon showing the dialog. The 'bug' is that the loading is overlayed by the file manager window. Is it sufficient to fix that order of windows? Or does it need an improvment to get to a shorter loading process at this time?

**Comment by hongcui** [comment]
we can shorten the loading time later.

On Mon, Jun 1, 2015 at 2:06 PM, rodenhausen <notifications@github.com>
wrote:

> It didn't start on close. It started upon showing the dialog. The 'bug' is
> that the loading is overlayed by the file manager window. Is it sufficient
> to fix that order of windows? Or does it need an improvment to get to a
> shorter loading process at this time?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biosemantics/etc-site/issues/250#issuecomment-107712403>
> .
>



-- 
Hong Cui, Ph.D <http://sirls.arizona.edu/hongcui>
Associate Professor, Information Technology
School of Information <http://sirls.arizona.edu>
University of Arizona
ETC Bi-Weekly Hangout
<https://plus.google.com/hangouts/_/calendar/YWhmaGYwcGoyOWVhYWRtc2RvOGtmazJxcDBAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ.7o85gqkjen62oksgqdjv4mir78?authuser=0>
Member of Plazi.org
