### ISSUE TITLE
source document information should be optional

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#257]
when the user enters author, year, title information for each individual entries in batch file creation for text capture, we should not attach empty author, year, title fields to the input. 
 
see http://screencast.com/t/3p7MQcWuJDOZ

**Comment by rodenhausen** [comment]
implemented as follows:
text takes precedence over textfield source document information on a treatment by teatment basis . If it's missing from text, the values of the fields are plugged in.
