### ISSUE TITLE
author, year, title attached to the end of the last entry

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#258]
may be confusing to the users. see http://screencast.com/t/aplbXWsst6
only attached to the last entry, see http://screencast.com/t/9IUyghab2

**Comment by rodenhausen** [comment]
>> if the user specifies author in his text at the end of a treatment
>>  should it reorganize the treatment to have author on top or leave the users

>no it shouldn't 

That means there is no order to be enforced between the different keys. Only that the source document info fields should be sorted in at the top. However again, no order between these can be enforced. For example, the user could give author at the end themself, hence order would already be broken when sorting these fields in at the top.
