### ISSUE TITLE
rewind option not available for a Text Capture task 

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#260]
I am at To Ontologies step, and the rewind option is grey-ed out. see

http://screencast.com/t/k7x5YqAzct

**Comment by rodenhausen** [comment]
this is obsolete since we are moving to ontologies to it's own task.

Also note, that rewind was meant to be only available when a task is complete. If not complete one can only resume. If it should be available in other situations in the context of other tasks, we would have to revisit this.
