### ISSUE TITLE
Nico Rubus case matrix selection bug

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#265]
For some reason the taxonomy hierarchy from Nico's 4 rubus test data are not shown corrected in the matrix selection view. Raw input pasted below:

author: Radford_Ahles_Bell
year: 1968
title: Manual of the Vascular Flora of the Carolinas
family name: Rosaceae Jussieu, 1789
genus name: Rubus Linnaeus, 1753
morphology: Woody plants with erect, arching or trailing, often thorny stems. The new shoots are commonly termed primocanes, in their 2nd year becoming the flowering and fruiting branches then termed floricanes, and then usually dying. Leaves simple, or ternately, pinnately or palmately compound; stipules present, persistent, adnate to the petioles. Inflorescence terminal on lateral branches, a panicle, cyme, corymb, raceme, or flowers solitary. Sepals 5, green, pubescent; petals 5, white, pink or magenta, (white flowered species may have pink tinted forms); stamens and pistils numerous. Fruit a drupelet, usually very juicy, the aggregate of numerous drupelets on a torus is commonly referred to as a “berry”.

author: Radford_Ahles_Bell
year: 1968
title: Manual of the Vascular Flora of the Carolinas
family name: Rosaceae Jussieu, 1789
genus name: Rubus Linnaeus, 1753
species name: Odoratus Linnaeus, 1753
morphology: Shrub, with erect or arching, thornless branches, the stems not rooting at the apex, the bark peeling from the stems. Leaves simple, 1-3 dm long and about as wide, palmately 3-5 lobed, finely, doubly serrate, lobes acute to acuminate; petioles about 1/ 2 as long as blades. Young stems, petioles and the principal veins on lower surface of blade pubescent with long, glandular, red trichomes. Inflorescence a compound flat-topped cyme, peduncles, pedicels and calyx covered with gland-tipped, red trichomes. Sepals triangular-ovate, 1.5-2.5 cm long, caudate; petals magenta, showy, 2-3 cm long. Drupelets pubescent, pinkish or purplish; aggregate depressed, ca. 1 cm long, 1-2 cm broad, hardly juicy, falling free from the torus;
phenology: June-Aug.; July-frost;
habitat: Woodland borders, rocky slopes, stream banks and often on road cuts or talus slopes; rots. [Va., Ga., Tenn., Ky., W.Va.]

author: Weakley
year: 2015
title: Flora of the Southern and Mid-Atlantic States
family name: Rosaceae Jussieu, 1789
genus name: Rubus Linnaeus, 1753
morphology: Trees, shrubs, or woody vines (with arching “canes” or climbing, arching, or scrambling stems); leaves simple or compound; ovary superior; fruit dehiscent (aggregate of follicles, or capsule) or indehiscent (drupe, aggregate of drupelets, aggregate of achenes); leaves alternate; fruit various; leaves large, > 10 cm wide, palmately veined, and pinnately lobed; fruit an aggregate of drupelets; leaflets > 10 mm wide, serrate or crenate; shrubs, trees, or woody vines (see below); flowers white, pink, or purplish; leaves palmately or 1-pinnately compound, generally with < 11 leaflets; inflorescences axillary or terminal panicles or corymbs with few (<15) flowers, the petals white, pink, or purplish (rarely yellow) and > 6 mm long; fruit a hip or aggregate of drupelets; arching or upright shrubs or climbing or sprawling woody vines, the stems usually armed with prickles; fruit an aggregate of drupelets, developing from a flattish or hemispheric hypanthium, with the ovaries and drupelets exposed; leaflets usually acuminate at the apex; leaflet margins serrate or doubly serrate.

author: Weakley
year: 2015
title: Flora of the Southern and Mid-Atlantic States
family name: Rosaceae Jussieu, 1789
genus name: Rubus Linnaeus, 1753
species name: Odoratus Linnaeus, 1753
morphology: Leaves simple; leaves palmately lobed, orbicular, coarsely toothed, 9-30 cm long; plant a shrub, 10-20 dm tall; petals deep pink;
phenology: Jun-Aug; Jul-Oct.;
habitat: Rocky upland forests, boulderfields, rock outcrops and clearings, moist roadsides, and thickets, especially on base-rich substrates. NS west to MI, south to w. NC, n. GA, and e. TN.

**Comment by rodenhausen** [comment]
should be related to not having correct identifier to populate tree structure of nodes. Probably related to taxon concept hierarchy.
