### ISSUE TITLE
Glossary uploading incomplete

### ISSUE THREAD

**Issue by clendara1** [biosemantics/etc-site#268]
Please be aware that the function that uploads the "term classification" in csv format is not uploading all the terms.  We are using the ETC Dev site, and we are working with a dataset of 3400 terms for which categories were assigned. Not all terms in pre-existing categories were populated, and none of the terms in new categories were uploaded, neither were the categories created.

**Comment by rodenhausen** [comment]
(1) wrong input format used that resulted in terms not being categorized;

(2) create new feature request to automatically create new categories from import data; https://github.com/biosemantics/etc-site/issues/271
