### ISSUE TITLE
Review step in Text Capture: context search

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#277]
"epigastric_fold" should match "epigastric fold". In other word, when search for context sentence, search both the original form and the form without - or _. 

input text:
author: Gonzalez
year: 2012
title: A revision and phylogenetic analysis of the spider genus Aysenia Tullgren (Araneae: Anyphaenidae, Amaurobioidinae)
subfamily name: Amaurobioidinae unspecified, unspecified
tribe name: Amaurobioidini unspecified, unspecified
genus name: Aysenia unspecified, unspecified
species name: elongata unspecified, unspecified
female1-morphology: Prosoma length 0.88, width 0.48, narrowed in front, slightly wider at leg III (Fig. 1b). Length of tibia/metatarsus: I, 0.40/0.30; II, 0.34/0.34; III, 0.22/0.20; IV, 0.32/0.20. Palpal tarsus length 0.28. Chelicerae strong, with thick anterior bristles, three contiguous teeth on retromargin, and three very small teeth on promargin. Sternum length 0.54, width 0.34. Spines: femora I-IV d 1-1-1. Leg I, tibia v 2-2-0; metatarsus v 2bas. II, tibia r1; metatarsus v r1-r1-0, p 1. III, tibia apparently 0; metatarsus v 1ap and apical group of thick setae. IV, tibia v p1-p1-p1; metatarsus v p1-2-comb (preening comb not in a definite line). Opisthosoma length 1.94, spiracle-epigastrium 1.18, spiracle close to spinnerets. Color in ethanol (Fig. 1a): Prosoma brown, legs pale yellow, darker distally. Opisthosoma pale yellow on the back with two longitudinal reticulated dark brown bands confluent at the hind-end; sides with longitudinally arranged, scattered short stripes of the same color; venter brown uniform. Epigyne (Fig. 3a): lateral lobes separate, median field and copulatory openings in epigastric fold, all weakly sclerotized. Spermathecae irregular, contiguous, copulatory ducts contorted. Accessory bulbs voluminous (Fig. 3a, Ramírez 2003: fig. 22c-d).
male-morphology: Prosoma length 0.94, width 0.56, narrowed in front, slightly wider on leg III (Fig. 2b). Length of tibia/metatarsus: I, 0.74/0.50; II, 0.52/0.38; III, 0.28/0.24; IV, 0.40/0.36. Palpal tarsus length 0.32. Chelicerae strong, with thick anterior bristles, three contiguous teeth on retromargin, and three very small teeth on promargin. Sternum length 0.52, width 0.36. Spines: femora I-IV d 1-1-1. Leg I, tibia v 2-2-0; metatarsus v 2bas. II, tibia v r1 or r1-r1-0; metatarsus v r1-0-0, p 1-0-0 or v r1-0-0, p1. III, tibia apparently 0; metatarsus v 1ap and apical group of thick setae. IV, tibia v p1-p1-p1; metatarsus v p1-p1-p1, d r1ap. Opisthosoma length 1.76, spiracle-epigastrium 1.04, spiracle close to spinnerets. Color in ethanol (Fig. 2a): As in female. Palp (Fig. 3a-c): Tibia short, width/length 0.32, RTA long, acute, wider at base. Cymbial conductor wide. Tegulum basal. Sperm duct with two conspicuous loops at anterior dorsal margin. Embolus long. Median apophysis apical, small and hook-shaped. Primary conductor with canal, heavily sclerotized in apical region. Secondary conductor well defined, without canal, separated from the apical tegulum by a suture. Paramedian apophysis with three cusps (Fig. 4c-d), one large, close to the median apophysis (rPMA), one small slightly sclerotized, close to the primary conductor (pPMA) and a small sclerotized one in between (iPMA).

author: Gonzalez
year: 2012
title: A revision and phylogenetic analysis of the spider genus Aysenia Tullgren (Araneae: Anyphaenidae, Amaurobioidinae)
subfamily name: Amaurobioidinae unspecified, unspecified
tribe name: Amaurobioidini unspecified, unspecified
genus name: Aysenia unspecified, unspecified
species name: huayun unspecified, unspecified
female-morphology: Prosoma length 2.02, width 1.08, slightly constricted between legs I and II (Fig. 12b). Length of tibia/metatarsus: I, 1.22/1.02; II, 1.12/0.94; III, 0.62/0.60; IV, 0.96/0.80. Palpal tarsus length 0.54. Chelicerae strong, with thick anterior bristles (Fig. 12d), three contiguous teeth on retromargin, distal one compressed, and three teeth on promargin, middle tooth larger. Sternum length 1.04, width 0.62. Spines: Leg I, femur d 1-1-1; tibia v 0-p1-2; metatarsus v 0-2-p1-p1. II, femur = I; tibia p 1ap; metatarsus v 2-p1-p1 or v 2-2-p1, p d1. III, femur d 1-1-1, p 1ap; tibia v 2ap or 0-r1-2; metatarsus v 2-0-2, p 0-1-1, r 1ap, d 2ap. IV, femur d 1-1-1; tibia v 2-2-p1, p v1bas, r 0-d1-d1-0 or v p1-p1-2, p v1-v1-0-0, r 0-d1-0-0; metatarsus d 2ap, v 2-p1-2, p 1ap, r d1-d1-0 or v p1-p1-2, r d1bas. Prolateral spines on tibia IV short and thick. Leg III oriented forward. Opisthosoma length 4.12, spiracle-epigastrium 2.32, spiracle-spinnerets 0.48. Color in ethanol (Fig. 12a): Prosoma reddish brown, lighter towards posterior region, ocular region dark. Chelicerae reddish brown. Legs yellowish brown with coxae and trochanters slightly lighter. Sternum brown. Opisthosoma grayish brown, with four pale yellow dorsal spots, two largest in the middle and four patches on posterior end, all covered by white hairs. Venter pale yellow uniform. Epigyne (Fig. 13): Median field and copulatory openings in epigastric fold. Lateral lobes separate, posterior half strongly sclerotized, with depressions. Copulatory ducts not coiled, ducts of accessory bulbs short, convergent. Spermathecae irregular, contiguous.
male-morphology: Unknown.

**Comment by rodenhausen** [comment]
can't reproduce. Don't get epigastric_fold as a term loaded. Only epigastric. Other terms such that follow similar pattern such as spiracle_spinnerets do show all contexts, i.e. spiracle-spinnerets occurences.

**Comment by hongcui** [comment]
To reproduce the problem, you should select 'Spider' glossary.
