### ISSUE TITLE
Issue with Matrix Generation

### ISSUE THREAD

**Issue by stevenchong** [biosemantics/etc-site#284]
I receive the error message "Failed to generate matrix", when trying to create a matrix with the Spiders taxon group and checking the Infer Absent/Present States box.  If I uncheck the box and leave the other settings unchanged, I am able to move on to the next steps in the process.  Leaving the Inherent Values box checked/unchecked doesn't seem to matter.

**Comment by rodenhausen** [comment]
should be fixed. If not need input files used.
