### ISSUE TITLE
Issue with Text Capture

### ISSUE THREAD

**Issue by stevenchong** [biosemantics/etc-site#285]
I am able to successfully create a new input file for the Text Capture tool by using the Batch Creation option.  However, when running the the Text Capture tool, choosing the Select Existing Folder option and navigating to the new file, I run into an error message "Input directory is not valid. Please select a valid input directory" after clicking on the Next Step button.  The directory is listed correctly but does not seem to be recognized.

I am able to work around this issue by downloading the new file and then uploading it to the Text Capture tool, so the input file appears to be okay.  After uploading, the Select Existing Folder option works correctly with subsequent files.

**Comment by rodenhausen** [comment]
I cannot reproduce this problem. Could you send me the text you used in the batch creation that led to the invalid files?

**Comment by stevenchong** [comment]
I cannot recreate the issue either.  It appears that it resolved itself
