### ISSUE TITLE
Batch Input Creation: Error reporing on missing taxon_name authority/date

### ISSUE THREAD

**Issue by clendara1** [biosemantics/etc-site#291]
I have not been able to run any analysis.  I uploaded the information - my dataset is Pilot 2 - shown in picture.
![prefailure](https://cloud.githubusercontent.com/assets/8581741/9701568/f34df70c-53fd-11e5-82dd-65bc813dd603.JPG)
I defined the folder - as shown
![failed1](https://cloud.githubusercontent.com/assets/8581741/9701569/015293da-53fe-11e5-8798-2ffaa688453b.JPG)
This is the message after clicking the "next step" button in the previous picture.
![failed2](https://cloud.githubusercontent.com/assets/8581741/9701572/06f6f5ec-53fe-11e5-99da-7e346d37e83f.JPG)

**Comment by rodenhausen** [comment]
When using malformed input like below, batch input creation should output that authority or date of genus name is missing.

Genus name: Cheilanthestba, tba
Species name: villosa tba, tba
Morphology: text...

missing space

Genus name: Cheilanthes tba, tba
Species name: villosa tba, tba
Morphology: text...
