### ISSUE TITLE
Help: mouse over

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#295]
Menu expands on mouse over, I think Help should have the same behavior. Currently you have to click on Help. http://screencast.com/t/zQg9RzHnaXn6

**Comment by rodenhausen** [comment]
I think to recall we made this decision because the help would disappear if
the user moves the mouse back to the content. It would not be possible for
him to read along the help while taking action in the content.
We could also mix things: let the help appear on mouse over and disappear
on click if that's desired.

**Comment by stockto2** [comment]
I think it makes sense for the file manager to appear on mouse over since
it is frequently accessed, but I don't think it would be necessary for
Help. It might become bothersome to have it always appear if the user
moused over the help button by accident.

**Comment by hongcui** [comment]
good points. How could we then indicate to the user that they need to click
on Help to close help? should we maybe have a tool tip?

On Tue, Dec 8, 2015 at 9:47 AM, stockto2 <notifications@github.com> wrote:

> I think it makes sense for the file manager to appear on mouse over since
> it is frequently accessed, but I don't think it would be necessary for
> Help. It might become bothersome to have it always appear if the user
> moused over the help button by accident.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biosemantics/etc-site/issues/295#issuecomment-162941734>
> .
>



-- 
Hong Cui, Ph.D <http://sirls.arizona.edu/hongcui>
Associate Professor, Information Technology
Director of Graduate Studies
School of Information <http://sirls.arizona.edu>
University of Arizona
ETC Bi-Weekly Hangout
<https://plus.google.com/hangouts/_/calendar/YWhmaGYwcGoyOWVhYWRtc2RvOGtmazJxcDBAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ.7o85gqkjen62oksgqdjv4mir78?authuser=0>
Member of Plazi.org

**Comment by hongcui** [comment]
a tooltip that says 'click on Help to open/close it"

On Tue, Dec 8, 2015 at 11:03 AM, Hong cui <hong1.cui@gmail.com> wrote:

> good points. How could we then indicate to the user that they need to
> click on Help to close help? should we maybe have a tool tip?
>
> On Tue, Dec 8, 2015 at 9:47 AM, stockto2 <notifications@github.com> wrote:
>
>> I think it makes sense for the file manager to appear on mouse over since
>> it is frequently accessed, but I don't think it would be necessary for
>> Help. It might become bothersome to have it always appear if the user
>> moused over the help button by accident.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/biosemantics/etc-site/issues/295#issuecomment-162941734>
>> .
>>
>
>
>
> --
> Hong Cui, Ph.D <http://sirls.arizona.edu/hongcui>
> Associate Professor, Information Technology
> Director of Graduate Studies
> School of Information <http://sirls.arizona.edu>
> University of Arizona
> ETC Bi-Weekly Hangout
> <https://plus.google.com/hangouts/_/calendar/YWhmaGYwcGoyOWVhYWRtc2RvOGtmazJxcDBAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ.7o85gqkjen62oksgqdjv4mir78?authuser=0>
> Member of Plazi.org
>
>
>
>
>


-- 
Hong Cui, Ph.D <http://sirls.arizona.edu/hongcui>
Associate Professor, Information Technology
Director of Graduate Studies
School of Information <http://sirls.arizona.edu>
University of Arizona
ETC Bi-Weekly Hangout
<https://plus.google.com/hangouts/_/calendar/YWhmaGYwcGoyOWVhYWRtc2RvOGtmazJxcDBAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ.7o85gqkjen62oksgqdjv4mir78?authuser=0>
Member of Plazi.org

**Comment by stockto2** [comment]
Another option would be to change the text of the button to "Show Help"
when the help window is hidden, and "Hide Help" when it is open.

If we want a tooltip instead, it could say "Click to toggle help window."

**Comment by hongcui** [comment]
Both are good ideas. First one is even better.

On Tue, Dec 8, 2015 at 12:47 PM, stockto2 <notifications@github.com> wrote:

> Another option would be to change the text of the button to "Show Help"
> when the help window is hidden, and "Hide Help" when it is open.
>
> If we want a tooltip instead, it could say "Click to toggle help window."
>
> On Tue, Dec 8, 2015 at 11:04 AM, hongcui <notifications@github.com> wrote:
>
> > a tooltip that says 'click on Help to open/close it"
> >
> >
> > On Tue, Dec 8, 2015 at 11:03 AM, Hong cui <hong1.cui@gmail.com> wrote:
> >
> > > good points. How could we then indicate to the user that they need to
> > > click on Help to close help? should we maybe have a tool tip?
> > >
> > > On Tue, Dec 8, 2015 at 9:47 AM, stockto2 <notifications@github.com>
> > wrote:
> > >
> > >> I think it makes sense for the file manager to appear on mouse over
> > since
> > >> it is frequently accessed, but I don't think it would be necessary for
> > >> Help. It might become bothersome to have it always appear if the user
> > >> moused over the help button by accident.
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >> <
> >
> https://github.com/biosemantics/etc-site/issues/295#issuecomment-162941734
> > >
> > >> .
> > >>
> > >
> > >
> > >
> > > --
> > > Hong Cui, Ph.D <http://sirls.arizona.edu/hongcui>
> > > Associate Professor, Information Technology
> > > Director of Graduate Studies
> > > School of Information <http://sirls.arizona.edu>
> > > University of Arizona
> > > ETC Bi-Weekly Hangout
> > > <
> >
> https://plus.google.com/hangouts/_/calendar/YWhmaGYwcGoyOWVhYWRtc2RvOGtmazJxcDBAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ.7o85gqkjen62oksgqdjv4mir78?authuser=0
> > >
> > > Member of Plazi.org
> > >
> > >
> > >
> > >
> > >
> >
> >
> > --
> > Hong Cui, Ph.D <http://sirls.arizona.edu/hongcui>
> > Associate Professor, Information Technology
> > Director of Graduate Studies
> > School of Information <http://sirls.arizona.edu>
> > University of Arizona
> > ETC Bi-Weekly Hangout
> > <
> >
> https://plus.google.com/hangouts/_/calendar/YWhmaGYwcGoyOWVhYWRtc2RvOGtmazJxcDBAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ.7o85gqkjen62oksgqdjv4mir78?authuser=0
> > >
> > Member of Plazi.org
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/biosemantics/etc-site/issues/295#issuecomment-162964139
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biosemantics/etc-site/issues/295#issuecomment-162994391>
> .
>



-- 
Hong Cui, Ph.D <http://sirls.arizona.edu/hongcui>
Associate Professor, Information Technology
Director of Graduate Studies
School of Information <http://sirls.arizona.edu>
University of Arizona
ETC Bi-Weekly Hangout
<https://plus.google.com/hangouts/_/calendar/YWhmaGYwcGoyOWVhYWRtc2RvOGtmazJxcDBAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ.7o85gqkjen62oksgqdjv4mir78?authuser=0>
Member of Plazi.org
