### ISSUE TITLE
UI review by Hong Dec 8: part I

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#297]
Home page:
1. see http://screencast.com/t/mbA5wejP: hide them, don't remove them yet.
2. description for Ontology Building: Allows to build taxon specific ontologies using the anatomical and character terms identified by Text Capture. Ontologies are optional for Matrix Generation, but having them help to generate less sparse matrices. 
3. description for Matrix Generation: semantic marked-up => semantically marked-up
4. Key Generation: Generates interactive identification keys from taxon-character matrices => Generates an interactive identification key from a taxon-character matrix
5. Taxonomy Comparison: 
two given taxonomies => two related taxonomies; 
a result from Key Generation => output from Matrix/Key Generation (under-development) 
conflicts and/or ambiguity => conflicts and/or ambiguities.
6. In Menu, remove Visualization.
7. In Menu, Sample => Sample Test Data, 

Sample page
1. update the title to 'Sample Test Data'.
2. Introduction => How to use the sample data:
3. The video is flash, as chrome is no longer support Flash, can you convert the video to some other format?

My Account:
User Information section:
1. Make Email a required field (we need a way to contact user when we need to purge old data)
2. For Bioportal User Id and Bioportal API key,  add explanatory text: "needed for submitting ontology terms to Bioportal"
3. Email Notification: add explanatory text "uncheck a box to disable the email notification function of a tool"
4. Link to Ontology Term Organizer (OTO): add explanatory text: "OTO is a community consensus-promoting term categorization application (http://biosemantics.arizona.edu/OTO). The terms categorized on ETC site can be directly imported into OTO with you as the owner of the term set. You and others can co-categorize the terms on OTO and help grow the consensus-based glossary/ontology for your group and improve the performance of biodiversity software applications including ETC tools." 
5. Link to OTO: OTO Account available => Already have an OTO Account?

News page:
ask Thomas to update the news.

File Manager: 
1. missing folder icon when expanding an empty folder: http://screencast.com/t/oMHXnr3f
2. edit file function is gone -- I can't edit a file any more.
3. update the instructions to:

Files you own and shared with you are listed here, including the files used as input to different tasks/analyses and the files output by the software. 
* Select a folder to activate usable buttons.
 
* To upload files, click on 'Owned', then 'Add Folder', then Select File Type, then 'Upload Files'.
 
* To create new files for Text Capture, first create the folder to hold the file, then click on 'Create Input for Text Capture' 
 
* Each task/analysis should have a folder, avoid mixing files and sub-folders in one folder.
 
* To start a tool, mouse over the Menu icon at left top corner of the page to expand it, then select the tool from the Menu.

**Comment by dongfang91** [comment]
Matrix Generation sub-menu: images about the steps.
