### ISSUE TITLE
UI review by Hong Dec 8: part II

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#301]
Text Capture:
1. Input requirements instruction, last sentence, remove "and Click Next".
2. Leave a blank line before 'To View, Edit or Delete ...files, go to File Manager'.
3. Create Files and Upload Files: make the two steps explicit, by marking them as 1. and 2. See http://screencast.com/t/T0iaQ66244w1
4. Select Existing Folder: http://screencast.com/t/Tk1pYjQA
5. Check 3 and 4 for Ontology Building, Matrix Generation, and Key Generation too and make them consistent. 
6. The 'Next Step' button should be specific to a task, change it to 'Next Step in Text Capture'. Check the 'Next Step' button in the Create Input step for all other tools. They should be 'Next Step in Ontology Building', etc.
7. Learn step: Add 'if email notification has not been disabled in Your Account' to 'You will be notified by an email when the process is complete'. Do the same for the Parse step (remove "If you didn't set up email preference")  

Ontology Building
1. "You are at"... step 2: Input => Define Task
2. INPUT REQUIREMENTS: "containing a XML files which conform to" => "containing XML files conform to"
3. Remove '1. If you do not have ... ' sentence. Add a radio button 'Create Files' just like Text Capture Create Input. If the user selects the 'Create Files' button, display "If you do not have an input folder ready, please run the Text Capture tool first to generate it. "

Matrix Generation
1. INPUT REQUIREMENTS: 
change the first sentence (it is the requirements for text capture) to:
"Matrix Generation takes an output folder of Text Capture as input.  MG's input files must be in English and conform to this format". [be careful the format should link to semanticMarkupOutput.xsd]
2. Similar to Ontology Building, add 'Create Files' option that leads to "If you do not have an input folder ready, please run the Text Capture tool first to generate it."
[I run into an invalid input error and had to stop here for MG, I think Thomas is working on the server now.]

**Comment by stockto2** [comment]
Concerning number 6: 

6. The 'Next Step' button should be specific to a task, change it to 'Next Step in Text Capture'. Check the 'Next Step' button in the Create Input step for all other tools. They should be 'Next Step in Ontology Building', etc.

It seems intuitive that

**Comment by stockto2** [comment]
Closed accidentally, reopening.

**Comment by stockto2** [comment]
UI Changes finished.
