### ISSUE TITLE
ETC site email notification

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#304]
Jocelyn Pender reported that she does not get email notification. She didn't uncheck email notification in Account.

**Comment by dongfang91** [comment]
Hong, I have checked this issue, found it works in etc-dev, could you check with Jocelyn Pender about that?

**Comment by ramorrismorris** [comment]
Most likely her spam filter is holding it. If not, I will show you how to
read mail outbound logs on the server.

From my mobile phone

**Comment by dongfang91** [comment]
Thanks, Bob. Don't need check logs, I have found the reason. When the user creates an account, although all email notifications show checked in My Account interface, they are not updated into server. 

The issue has been fixed.
