### ISSUE TITLE
Matrix Generator fails

### ISSUE THREAD

**Issue by danveno** [biosemantics/etc-site#325]
Matrix Generator can not generate matrix from the output file directly obtained from Text Capture.

Sample XML file is attached.

[Vivrette2006_SPECIES_AizoaceaesMartinovs2006.txt](https://github.com/biosemantics/etc-site/files/92623/Vivrette2006_SPECIES_AizoaceaesMartinovs2006.txt)

![image](https://cloud.githubusercontent.com/assets/5811267/12367222/a380fdfc-bb9d-11e5-92f1-ddea160ddfc3.png)

**Comment by rodenhausen** [comment]
enhanced_constraint not allowed by schema. https://github.com/biosemantics/charaparser/commit/64fbb6188570200869ac2a03ef591460ed9f3c01
