### ISSUE TITLE
copy shared to owned

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#326]
I started a TextCapture task using a folder in my shared (the third folder in shared). System informed me that the file will be copied to my space, then when I go to File Manager, I see a folder, named "tet" (why is that name?), with zero files. 

![image](https://cloud.githubusercontent.com/assets/831423/12367332/58437cba-bb9e-11e5-99ee-34eb1e22b7ef.png)

**Comment by rodenhausen** [comment]
I cannot reproduce that problem
