### ISSUE TITLE
shorten file names created by input creation

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#330]
For example, the following original filename:
A. B. Arun1, Wen-Ming Chen2, Wei-An Lai3, Jui-Hsing Chou3, Fo-Ting Shen3, P. D. Rekha1 and Chiu-Chung Young2009_genus_Lutaonella_species_thermophila_strain_number_CC-MHSW-2.xml
would be simplified to:
Lutaonella_thermophila_CC-MHSW-2_Arun_2009.xml

and an xml description of a genus:
A. B. Arun1, Wen-Ming Chen2, Wei-An Lai3, Jui-Hsing Chou3, Fo-Ting Shen3, P. D. Rekha1 and Chiu-Chung Young2009_genus_Lutaonella.xml
would be simplified to:
Lutaonella_Arun_2009.xml.

**Comment by rodenhausen** [comment]
do you want the authority and date of the rank to be ommited in the filename?

**Comment by hongcui** [comment]
I think our formula is

first author's last name + taxon name + pub date [taxon authority + date].xml

when either authority and date is unknown, do not include them in the file name. 
taxon name should include only the names, not the rank.

**Comment by dongfang91** [comment]
This is one example in spider case. I omitted authority and date. There are no constraints for the taxon authority and date, they can be any string, like"un", "unspecified", or "unknown" etc, so it might be easier to only keep "first author's last name + taxon name + pub date"
![file manager 1](https://cloud.githubusercontent.com/assets/12636365/12663413/4b7b82ec-c5e5-11e5-91ed-1c44882a4337.png)

**Comment by dongfang91** [comment]
family,genus.          keep genus
class,family         keep family
family genus specie       keep genus specie
genus specie subspecie       keep    genus specie subspecie
