### ISSUE TITLE
Input UI

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#333]
Minor changes to make the page look neater. 

In Create Files and Upload Files options, we could add the text "Create Files: " before the Create Files button and "Update Files: " before the Upload Files button. 

![image](https://cloud.githubusercontent.com/assets/831423/12629993/7729088a-c507-11e5-9006-debad7e1b62b.png)

In Select Existing Folder option, put a textbox in front of the button to display the selected folder:
![image](https://cloud.githubusercontent.com/assets/831423/12630040/ac6da9ba-c507-11e5-83ed-abb447f334f8.png)

Do the same for  the Define Task page:

![image](https://cloud.githubusercontent.com/assets/831423/12630200/96762406-c508-11e5-91ce-8fa0a23d8dd0.png)

**Comment by hongcui** [comment]
Change Create Files to Create Input Files, 
Change Upload Files to Upload Input Files. 

Switch positions for  'Choose one of the following ...."  and "To View, Edit, or Delete ...."

**Comment by dongfang91** [comment]
fixed
