### ISSUE TITLE
resume/start new task

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#335]
How about we change the layout of this popup window from

![image](https://cloud.githubusercontent.com/assets/831423/12630299/128f2c86-c509-11e5-8ca2-0a0b6831612c.png)

to something like: 
------------------------------------------------
start or resume a task?               
------------------------------------------------
[start a new task]
           or
[select a task to resume]

list of tasks....
------------------------------------------------

**Comment by hongcui** [comment]
Tasks should be listed as

Text Capture task **test** [paused at Review Terms step]

**Comment by dongfang91** [comment]
We decided to hide this dialog!
