### ISSUE TITLE
extra folder generated by Text Capture?

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#342]
I run a task, ended up with two output folders:
![image](https://cloud.githubusercontent.com/assets/831423/12632180/3fe43ed8-c513-11e5-99fd-ec17e15e9909.png)

**Comment by dongfang91** [comment]
test_outputTR folder contains term categorization files.

**Comment by rodenhausen** [comment]
Remember, we need the term categorization results for input to matrix
generation (enhance glossary initialization)

**Comment by hongcui** [comment]
change the folder name, replace "outputTR" with 'terms'
