### ISSUE TITLE
Creating a new task 

### ISSUE THREAD

**Issue by clendara1** [biosemantics/etc-site#344]
I am starting a new task using "Text Capture" and I keep on getting the same box to select a task, that replicates if I hover over it.  

![bug](https://cloud.githubusercontent.com/assets/8581741/12933205/f20fa30e-cf54-11e5-95d5-985aa64d1ded.JPG)

check that I have selected a different folder (Model system), but this task box with the bird task keeps on appearing.  I logged out and then logged in and it reappear.

**Comment by dongfang91** [comment]
We decided to hide this dialog, so each time when user click the tool, ETC will directly create a new task no matter there is an existing task.
