### ISSUE TITLE
File Manager:Create Input review

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#348]
1. file counts not updated when new input files have been created and added to a folder. See
![image](https://cloud.githubusercontent.com/assets/831423/13290766/63b90472-dad2-11e5-847e-98686228bdbb.png)

2. In this test, I didn't use "#....#" to enclose descriptions that span multiple paragraphs -- this resulted an entry marked with the red box below. The errors are detected, but the error messages is not clear:

Don't know what is.  => Field "" should not be used. 
No rank and name is given => should be consistent with the style of other errors: e.g., "You need to provide a rank and a taxon name for each description entry."
The last error message in the screenshot needs to be updated to include also elevation description type:

![image](https://cloud.githubusercontent.com/assets/831423/13291232/34ee5906-dad4-11e5-8eae-f712fa484e04.png)

accordingly, update instructions below:

![image](https://cloud.githubusercontent.com/assets/831423/13291302/7b697e56-dad4-11e5-906d-47170b55176c.png)

3. File names should only include the last name of the first author, but when I have

author: Fernald, A; Fernald, A; Fernald, A

the file name generated include all names, see below:
![image](https://cloud.githubusercontent.com/assets/831423/13291835/92703980-dad6-11e5-941e-75d4d31b7e01.png)

**Comment by rodenhausen** [comment]
1. fixed
