### ISSUE TITLE
Create Input step: more issues

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#353]
1. The options should all be reset in Create Input step when the user start a Text Capture task. see http://screencast.com/t/6BOhWN4Gciw.

2. Should not allow UploadFiles in New Folder before a New Folder is created. see http://screencast.com/t/CGypigGyeM8t

3. Not sure why 'etc-dev says' message box is popping up (after clicking on Create new Folder)
![image](https://cloud.githubusercontent.com/assets/831423/13330940/73dea58c-dbb8-11e5-9a4b-2016a08e5fa4.png)

**Comment by dongfang91** [comment]
I cannot reproduce question 3, it could be some constraints on your browser.
