### ISSUE TITLE
Term Review: comments not shown

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#356]
comment saved for a term, but when use the Comments menu to show all user comments, nothing is shown. Comment can still be seen by right-clicking the term. 
http://screencast.com/t/TIx9N5Fo2

**Comment by rodenhausen** [comment]
can't reproduce

**Comment by hongcui** [comment]
The issue is still there. http://screencast.com/t/1VXcmjMg

**Comment by rodenhausen** [comment]
This was related and should be resolved now.
