### ISSUE TITLE
about Preprocess step (Text Capture)

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#357]
Move buttons (change to icons): 
![image](https://cloud.githubusercontent.com/assets/831423/13334217/27dc55de-dbc8-11e5-9502-ad99d24a3e55.png)

Should show the count on the top of the text area: how many descriptions need to be corrected and how many have been corrected. 

Bracket counts: should only show the brackets with a count greater than 0. Also should change to label to "Unmatched brackets:".

Another  user reported:
When Preprocessing for a new task begins, the screen shows the Preprocess text box/screen from the last task. This is confusing at first. => should reset the box.

Previous Description button does not work: see http://screencast.com/t/sV8QojCH0PZS

**Comment by dongfang91** [comment]
change the buttons to icons: I think these icons might not be clear for users, maybe still keep the button. I move the button above.

**Comment by dongfang91** [comment]
Previous Description button:  when the description is corrected, the description will disappear. In this page, it only shows the descriptions with unmatched brackets.

**Comment by dongfang91** [comment]
fixed
