### ISSUE TITLE
Ontology Building:IRI not supported?

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#361]
see this video 
http://screencast.com/t/9xuWzZ6k

can't save a submission because IRI is not supported? The same task shared with Thomas.

**Comment by rodenhausen** [comment]
We use as Quality http://purl.obolibrary.org/obo/PATO_0000001
and as Entity http://purl.obolibrary.org/obo/CARO_0000006

The IRI used in the video is subclass of neither but that's currently a requirement. Let me know if that's wrong.

**Comment by rodenhausen** [comment]
we relaxed the requirement that classes with existing external IRIs need to be already subclass of PATO quality or CARO entity.
