### ISSUE TITLE
Matrix Generation: Select Input

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#362]
see issue #359, the same issues are also presented in this UI.

In addition:

1. The INPUT REQUIREMENTS instruction should be replaced with the instruction for Matrix  Generation. Currently show instruction for Text Capture.

**Comment by hongcui** [comment]
The same issue reoccurred. Please fix it again. Also the move the instruction on File Manager to the first paragraph

**Comment by rodenhausen** [comment]
I could not see or trigger any of the issues reported in #359 for the relevant matrix generation views.

**Comment by rodenhausen** [comment]
> Also the move the instruction on File Manager to the first paragraph
What needsd to be done for this?

**Comment by rodenhausen** [comment]
> In addition:
> The INPUT REQUIREMENTS instruction should be replaced with the instruction for Matrix Generation. Currently show instruction for Text Capture.

This has been done

**Comment by dongfang91** [comment]
fixed by Thomas
