### ISSUE TITLE
Matrix Generation: Define Task and Generate

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#363]
Button and box order should be consistent

![image](https://cloud.githubusercontent.com/assets/831423/13338584/9bac21da-dbdf-11e5-8ac0-ad5439f62a6b.png)

Generate step: instruction "If you didn't set email preference ..." change to "If email notification is not disabled in My Account, you will ...." Check other tasks

**Comment by dongfang91** [comment]
fixed
