### ISSUE TITLE
Key Generation: Create Input

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#364]
I am trying to make the UI look consistent with other pages. Here is my suggestion:

![image](https://cloud.githubusercontent.com/assets/831423/13338995/9af10c1c-dbe2-11e5-8520-f2e96c5fad3e.png)

I'd like all "Create Files" labels changed to "Create Input Files" , "Upload Files" to "Upload Input Files" in Create/Select Input UIs of all ETC tools.

**Comment by dongfang91** [comment]
fixed
