### ISSUE TITLE
Taxonomy Comparison - Character Comparison ordering

### ISSUE THREAD

**Issue by hacole** [biosemantics/etc-site#425]
The Character comparison is really neat.

1 - I am wondering what is controlling the order that the characters are listed?
![untitled2](https://cloud.githubusercontent.com/assets/17579450/13475357/9c715b0e-e07f-11e5-810a-2b4a69b8b6dc.jpg)
 I think it would be more effective if the characters on both side of the comparison were listed the same way (eg. alphabetical). 

In my testing, characters that were present on both sides, were not in the same order, and it makes it difficult to navigate/compare.

2- Would be great to have the 'expand/collapse/ all options in the interface also.

**Comment by hongcui** [comment]
click on one in left, try to highlight the matching ones on the right
