### ISSUE TITLE
Text Capture: Input batch creation misses author on malformed input

### ISSUE THREAD

**Issue by rodenhausen** [biosemantics/etc-site#461]
Creates XML input that misses author information on taxon_name element if something like
family name: Rosaceae,Linnaeus,1735
is used to create the input. (notice comma instead of space between name and author). This will be invalid according to our schema.

Do we want a validation against the schema after creating input with batch?

TODOS:
1) Batch creation: Validation that all required fields that can be found in the XML schema are being set from the text given in batch creation.
2) Batch creation output: Plain schema validation
3) Single file creation: Validation that all required fields that can be found in the XML schema are being set from the form filled by user.
4) Single file creation: Plain schema validation
5) Text capture output: Plain schema validation

What's the desired consequences/UI behavior if validation fails for either of these scenarios?
1) - 4) report the errors to the user and explain how to correct the errors if possible. Let the user correct the issue and try again. 

5) 
a. Pack the invalid output files and corresponding input files and submit an issue "Invalid Text Capture Output" to CharaParser issue tracker on github along with a zipped folder containing the files.  And email the same to Hong.
b. Report an 'An internal error has occurred and the task is not completed. The issue has been reported to the system developer' to the user. When the user clicks 'OK', return the user to the home page.  In Task Manager, set the task status to 'failed'.

**Comment by dongfang91** [comment]
For 5) a , I just send email notification and pack the input and output files to Hong.
