### ISSUE TITLE
Task screen bug

### ISSUE THREAD

**Issue by clendara1** [biosemantics/etc-site#465]
We have been experiencing in both PC or Macs using Chrome the following bug.  Everytime we hit "text capture" the box of tasks appears and will remain in other screens, and we cannot get rid of it.

![bug](https://cloud.githubusercontent.com/assets/8581741/14025896/9b692b6c-f1c6-11e5-8b27-5dc4574cd772.JPG)

In the following image, please notice that the name of the buttons are not alingned with the boxes.

<img width="1115" alt="screen shot 2016-03-24 at 1 11 48 pm" src="https://cloud.githubusercontent.com/assets/8581741/14025880/8bd484e4-f1c6-11e5-9943-1b9f5954fbf2.png">

**Comment by rodenhausen** [comment]
This is already solved in the latest development commit
