### ISSUE TITLE
File Manager:wrong error message

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#478]
I input the following

![image](https://cloud.githubusercontent.com/assets/831423/14618431/6b146472-0567-11e6-9f91-ade3f7cf84c7.png)

![image](https://cloud.githubusercontent.com/assets/831423/14618374/2be175e2-0567-11e6-9d34-7a25777867db.png) 

when click on 'Create', got the error:
![image](https://cloud.githubusercontent.com/assets/831423/14618332/f4621428-0566-11e6-94a5-3062aceb1cd5.png)

**Comment by dongfang91** [comment]
fixed! 

To create descriptions, user need click "Add Description!"

**Comment by hongcui** [comment]
It is not fixed. see http://screencast.com/t/UP5T2NCB
