### ISSUE TITLE
File Manager: instructions for Batch Creation

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#479]
** 1. "Specifying Taxon Names" says to use 'unspecified' for unknown authority/date, but the error message says to use 'unknown'. Change to 'unspecified' for both. **

**2. Required/Option Fields: use bullet points to list the instructions -- like other instruction windows. Replace the text with the following:**

Required (in bold) and optional (in italic) fields for a taxonomic treatment are listed below:

- Require **author**, **year**, and **title**: specify in Source Document Information or Taxonomic Treatment Area.
- Require at least one **ranked taxon name** (including strain number), for example genus name, strain number (see also Specifying Taxon Names).
- Require at least one description of type **morphology, phenology, habitat**, or **distribution**. A scope may be applied to each description type in the format of "scope-description type". For example, male-morphology, fruiting-phenology, see also "Specifying Taxon Descriptions".
- Optional fields related to strain number: _equivalent strain numbers_, _accession number 16S rrna_; _accession number genome sequence_.
- Optional: _previous or new taxonomic names_

**3. Add in "Specifying Taxon Names" a new bullet: Use comma to separate multiple values in optional fields _previous or new taxonomic names_, and _equivalent strain numbers_.**
 
**4. Specifying taxon descriptions**: ".... between the paragraphs**,  and** enclose all the paragraphs with ..."

**5. Input Error: error message: One example:**

Don't know what field "strain name" is in the treatment: 

"morphology=ss  **why morphology show up as the first field in the error message?**
author=saké and saké
title="what is this"
strain name=ss tt , 1902
year=1987".
You need to provide at least a Taxon Name Information or Strain Information in the treatment:
**change to You need to provide at least one taxon name or one strain number in the treatment:**
"morphology=ss
author=saké and saké
title="what is this"
strain name=ss tt , 1902
year=1987".

**Comment by dongfang91** [comment]
fixed. Reorder the sequence for 5. input error: error message.

**Comment by hongcui** [comment]
Bold the following phrases:

Require at least one description of type **morphology, phenology, habitat,** or** distribution.** A scope may be applied to each description type in the format of "scope-description type". For example, male-morphology, fruiting-phenology, see also "Specifying Taxon Descriptions".
