### ISSUE TITLE
TextCapture: Preprocess instruction

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#481]
**Needs tidy up. Current:**
![image](https://cloud.githubusercontent.com/assets/831423/14620223/6fea656a-0570-11e6-94b1-5b5c37edf380.png)

**Change to **
![image](https://cloud.githubusercontent.com/assets/831423/14620567/3e31b24c-0572-11e6-9eac-5e8daef4f107.png)

Also add tool tip to the backward/forward button: "previous description" and "next description"

**Comment by dongfang91** [comment]
done
