### ISSUE TITLE
TextCapture:Term Review: multiple categories terms

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#484]
See

![image](https://cloud.githubusercontent.com/assets/831423/14621239/41001f00-0576-11e6-82f2-dc4fe710837c.png)

Two 'armed' are listed on the top in addition to the folder 'armed'. 

Here is what I did: with Term Groups tab shown,  I copied 'armed' from architecture to duration, then I clicked on Multiple Categories Terms. http://screencast.com/t/AuPQzWas731O

**Comment by rodenhausen** [comment]
should be resolved now, even though I never ended up in the exact same situation as you trying to reproduce. See http://screencast.com/t/tsHZvOFc
