### ISSUE TITLE
Task Manager:Share

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#499]
Need an error prevention measure. 
see
http://screencast.com/t/IYOnxOSuChP

**Comment by hongcui** [comment]
The issue is not fixed as of today.

**Comment by rodenhausen** [comment]
I propose this:
1. I will add headers to both lists: "Available users", "Shared with"
2. I will add two buttons to the dialog: a) Share b) Cancel
3. When the user clicks Share we will summarize what has changed and ask him to confirm. For example, in the cases you demonstrated we would say: You added 0 users to and removed 0 users from the share. Do you want to continue?

**Comment by hongcui** [comment]
I like this solution: How about a)Share b) Unshare for the buttons.

The message should not be a sentence, it would be better to make two phrases:
0 users added to shared list
0 users removed from the shared list.
