### ISSUE TITLE
TextCapture: Input

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#502]
Should not allow CreateFiles in New Folder before a New Folder is created. see http://screencast.com/t/CGypigGyeM8t: the issue with UploadFiles was fixed, but CreateFiles option still have the same problem. 

Check ALL INPUT step for all tools. 

also
![image](https://cloud.githubusercontent.com/assets/831423/14727073/65a56ec4-07dc-11e6-8917-7155721e3bc7.png)

**Comment by dongfang91** [comment]
Hong, I cannot reproduce this problem. It gives clear error messages when you didn't choose/create any folder.
