### ISSUE TITLE
Matrix Generation: Generate

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#509]
1.  ![image](https://cloud.githubusercontent.com/assets/831423/14890429/6cca1c6e-0d17-11e6-913b-f7713777ee60.png)

Change Review Matrix to Next Step in Matrix Generation; change Output Matrix to Download Matrix Now.

**Instructions and the buttons (shown in []) should look like:**

A taxon-by-character matrix has been generated.

[Next Step in Matrix Generation] Review the matrix in the next step. Taxa and characters will be presented first for you to select and load as a matrix.

[Download Matrix Now] Download the raw matrix to review it offline. The matrix will also be saved as '...........................[filepath/name]" in your File Manager.

**The download button should allow the user to download the matrix right away, and also output the matrix to user's OWNed folder**
 
2. Also the "Generate Matrix Using this output" button at the last step of text cature seems to work, but in Matrix Generation Define Task step, the "Selected input folder" is shown as 'SHARED/....'. I think it should be 'OWNED/...' May be just a typo.

3. rewording:
![image](https://cloud.githubusercontent.com/assets/831423/14890378/33fbfede-0d17-11e6-9d6b-04efa9386990.png)

**Comment by rodenhausen** [comment]
> Also the "Generate Matrix Using this output" button at the last step of text cature seems to work, but in Matrix Generation Define Task step, the "Selected input folder" is shown as 'SHARED/....'. I think it should be 'OWNED/...' May be just a typo.

**Comment by hongcui** [comment]
SHARED/ vs. OWNED/ issue persists on my screen. This is how I got it

http://screencast.com/t/ebEgpe4NlbSw

Also there is a new issue: Failed to save Matrix error pops up here and there. One instance is captured in the above video.

**Comment by dongfang91** [comment]
The problem was in the code public String shortenPath(String filePath)

fixed!

**Comment by hongcui** [comment]
at this time the instruction following the Download Matrix Now button, says the matrix will be saved in SHARED/..., is that right? Shouldn't it be OWNED? Just a question.

**Comment by dongfang91** [comment]
should be Owned. The same code problem, already fixed!
