### ISSUE TITLE
Taxomony Comparison: Define task

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#518]
![image](https://cloud.githubusercontent.com/assets/831423/15031531/3bc8d6e0-120e-11e6-8176-f6e3d8107a34.png)

The green arrows show the selected file paths are in different format: one without OWNED\, why?

Also I wonder if organizing fields by taxonomies will make the paper easier to understand -- 
taxonomy 1
    author
    date
    reviewed terms
taxonomy 2
    author 
    date
    reviewed terms
ontology

**Comment by dongfang91** [comment]
In define step, failed to reselect taxonomy folder, not show in the define interface!

**Comment by dongfang91** [comment]
Fixed for label related issues.
