### ISSUE TITLE
Matrix Generation: failed to generate a matrix

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#530]
I shared the text capture task with Thomas. The output there lead to the error:
![image](https://cloud.githubusercontent.com/assets/831423/15129025/1517b73e-15f4-11e6-9f8e-76663530e36d.png)

**Comment by rodenhausen** [comment]
The classpath was not populated with all the correct libraries. There were
elk 0.4.1 and 0.4.2 libraries mixed for some reason. I generated the matrix
generation classpath like described in useful notes and ended up only with
0.4.2. Now it works.
