### ISSUE TITLE
definitions for categories

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#544]
dragging terms to their categories will trigger a trace of category definitions and block the categorization process. Users suggested to hide definition trigger in the popup menu.

**Comment by dongfang91** [comment]
fixed. The definition trigger was not hidden, but when the cursor moved around the labels, it would disappear very soon, and would not block the categorization process.

**Comment by dongfang91** [comment]
Here is what it looks now. The definition message shows in the center of the screen.
![desctop screenshot](https://cloud.githubusercontent.com/assets/12636365/17786343/44c44bb6-6539-11e6-9e15-7cb877e9f38d.png)
![desctop screenshot1](https://cloud.githubusercontent.com/assets/12636365/17786345/485f9852-6539-11e6-8509-acd5cff461a3.png)
