### ISSUE TITLE
mixed units in matrix generation

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#548]
when descriptions include mixed cm and mm units, the user would like the units to be standardized to one (smaller unit, mm) in the matrix.

**Comment by rodenhausen** [comment]
A starting point: https://github.com/biosemantics/matrix-generation/blob/master/src/main/java/edu/arizona/biosemantics/matrixgeneration/transform/complete/NormalizeUnitsTransformer.java

**Comment by dongfang91** [comment]
Add a normalization functions into the matrix generation spreadsheet view menu, let the user select the unit they want to be normalized as, and the characters they want to normalize.
