### ISSUE TITLE
[Term Review] Show context only on request (context menu -> show context)

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#561]
Could you also import the source for the terms in Steven's ontology?

**Comment by hongcui** [comment]
found the function, but it does not follow our Term Review design. I had expect to bring up the context by clicking on a term. I should we should stay consistent .

**Comment by rodenhausen** [comment]
Do we want to make it consistent by adapting term review or ontology building?
Do you have an idea what the users would prefer? 
I did it differently this time because I wanted to avoid the "loading" every time a new term is selected, even though the user may not care about context.
