### ISSUE TITLE
[Ontology Building] synonym 

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#567]
Dragging a term in Synonyms does not seem to work, 

see http://screencast.com/t/WkWOiAH8No

**Comment by rodenhausen** [comment]
Do you have an active filter on the synonyms grid?

**Comment by hongcui** [comment]
no, I didn't. I have another similar issue http://screencast.com/t/TYew0WQgA36w

**Comment by hongcui** [comment]
correction, yes, I did have filter. That was the problem

**Comment by hongcui** [comment]
Well that says we definitely need to have a strong indicator to show if the filter is on or off. Can we move Filter to the end of the row and then show the term after the Filter button when the Filter is on?
