### ISSUE TITLE
[Ontology Building]The number of subclasses is not right in the tree visualization

### ISSUE THREAD

**Issue by CathyYujie** [biosemantics/etc-site#587]
![image](https://cloud.githubusercontent.com/assets/22200814/18652288/046e5168-7e86-11e6-9219-dd1721048cc3.png)

For example, the coloration has 16 subclasses in Categories, but there is just 3 in Tree Visualization.
Maybe just appears the subclasses who has subclasses.

**Comment by rodenhausen** [comment]
This is the normal behavior as we have discussed it so far in regards to
the requirements of this project.

For the filter on the grid: All rows are shown where any of the terms in
that row contains the filter.
For the filter on the tree: All nodes are shown where any of the nodes
contains the filter + All their parents until the root is reached + All
their children recursively.

How would you like it to be?

**Comment by rodenhausen** [comment]
You can't necessarily view tree and grid as being synchronized in what data they show. The simple example is where you have two different filters on each of them.

**Comment by CathyYujie** [comment]
I am sorry.
We get a wrong understanding about our operations.

The function is right. You can just close this issue.
