### ISSUE TITLE
[Ontology Building] Make Synonyms

### ISSUE THREAD

**Issue by CathyYujie** [biosemantics/etc-site#588]
1 Objective
This function is used to make synonym relations of terms in groups. 
It will be more convenient for users to do like this than to drag terms or input synonym words one by one.

2 Process
2.1 Data choose  and Function entrances
1) candidate terms, including folder name and specific words or phrases
2) All terms in grid, including Categories(superclass, subclass), Parts(parent, part)
![image](https://cloud.githubusercontent.com/assets/22200814/18819884/fe14fb8e-834c-11e6-8dd9-37d46fe79aed.png)
When click on or right click on the terms above, “Make synonyms” should be shown between “filter” and “Show Term Context” like the following picture

2.2 Main interface and operations
![image](https://cloud.githubusercontent.com/assets/22200814/18819872/cd26398e-834c-11e6-9e51-f3707d311027.png)
1) Users can find this by clicking on the word in candidate terms and grid
2) The name of this function is “Make synonyms”
3) Available terms are chosen from the current group of the chosen word, do not consider about other groups the word in
4) The word you click on will be one synonym term in “Synonyms” in the hover
5) Users can choose terms in Available terms by click on the terms and add them into “Synonyms” by the right arrow.
6) The first term in “Synonyms” will be the preferred term which should be differed from other words by different color and with tag “preferred term”. User can also put other words in “Synonyms”  to the top by “up arrow” button.

2.3 Relations between the chosen word and the existed synonyms
1) if the chosen word is already a synonym of one preferred word
It won't be happened in the categories and parts grid.

2) if the chosen word is already a preferred word
just add more synonyms.

2.4 Jump after complete
After users complete the operations in the hover and click the “OK” button, the page will jump to the tab “Synonyms” like the following:
![image](https://cloud.githubusercontent.com/assets/22200814/18819878/dfc2f474-834c-11e6-8756-af4d627a4789.png)

2.5 Related data change
1) Candidate terms
The color of the words added into synonyms need to be changed to light gray in the Candidate terms.
2) Synonyms
The words added into synonyms should appear in the Synonym tab.
3) Categories and Parts
Synonym terms should be replaced by the preferred term. If there are more than one words be replaced, just display once in a row.

3 Issues not determined
3.1 the name of the hover
Question: “Select synonyms for ‘chosen word’” is bit too long.
Solution: need Steven help?
3.2 tips
Question: Need a more suitable sentence to describe the source of “Available terms” which are coming from the same group of the chosen word in.
Solution: need Steven help?
3.3 display of preferred term
Question: The preferred term in “Synonyms” in the hover should be highlighted and differentiated from other synonym words.
Solution: Give the first word in the “Synonyms” a different font color and suffix tag “preferred term”.

**Comment by rodenhausen** [comment]
If I understand correctly, above group stands for a row in the grid?

We still have to define how to handle existing synonym relationships. 

1) If a term of a row is already the synonym to another preferred term outside of the row, do we agree that it should not be shown anymore in the view? If a term of a row is already the preferred term to other terms (some part of the row, others outside of the row) what are we going to show? What if none are part of the row and only outside of the row? Do we agree that a term cannot act as preferred term in one relationship and as synonym in a second?

2) Should existing relationships of the current preferred term be shown in the list, even though they are not part of the selected row? 

I will assume no until further discussion.

3) In case a "to be preferred term" is already a synonym of another term, do we agree that the desired behavior would be to not allow the user to make this term the "preferred term" in the view? I.e. if the user clicked on a term in the grid that is already a synonym to another preferred term the view would be initialized such that nothing is pre-populated in the synonyms list?

I will assume that we agree on this until further discussion.

4) A scenario that should be considered when making these decisions should also be: If synonym terms are moved around (effectively switching the preferred term to another), what is supposed to happen?

**Comment by rodenhausen** [comment]
5) How should we deal with a scenario where the row looks like:
> a b c d e 

and we already have defined synonym relationships as
> a b
> c d

If we had the goal to initialize the view with existing relationships inside the row then we can't make two terms the preferred term.

**Comment by CathyYujie** [comment]
01 Problem
1) Terms used in category or part relations could not be added as synonyms
if one term is added in the synonyms, it should not be added or used in subclass or part relations. It’s logical.
But from the reverse, when one term is used in category or part relations, is it not allowed to be added as synonyms? The current function does not allow to add a used term to be synonym. It seems unreasonable to me.
![image](https://cloud.githubusercontent.com/assets/22200814/19323024/156a3ada-9070-11e6-8732-1b895a59aa17.png)

2)superclass also be added as available terms when we select synonyms for subclass terms
![image](https://cloud.githubusercontent.com/assets/22200814/19323035/21f69910-9070-11e6-9763-d939444d5ac5.png)

02 User-unfriendly
1) difficult to find the new added synonyms
It’s difficult to find the new synoyms you added in the synonym grid.
first, can we jump to the right page where the new added term in? right now, it jumps to the synonym tab at the first page.
second, maybe we can give the new synonyms a new background color to highlight them. wherever you click on screen, the background color will disappear.
![image](https://cloud.githubusercontent.com/assets/22200814/19323047/2f7585f6-9070-11e6-9212-6d13dccb16e6.png)

2) it’s hard to understand the choose for “no”
![image](https://cloud.githubusercontent.com/assets/22200814/19323056/3bb44fc8-9070-11e6-8603-e25a0be68305.png)

3) it’s hard to click on the right one when there are too many choice
It’s very covenient to drag words to realize the function of selecting the synonyms and the preferred term. 
In this case, we just need three buttons “move selected up”, “add selected”,“remove selected”at most.
![image](https://cloud.githubusercontent.com/assets/22200814/19323065/49b87e28-9070-11e6-97e1-7dc659d36ba2.png)

03 does not match the demand
1)the title should be select synonyms for “selected term”
![image](https://cloud.githubusercontent.com/assets/22200814/19323083/5eb4423a-9070-11e6-8f26-969b52c7d99e.png)

2) lack of an instruction about the availabe term
![image](https://cloud.githubusercontent.com/assets/22200814/19323091/69f6cdac-9070-11e6-8e93-1a60acfd5dc8.png)

04 Problem remains
subclasses do not appear when first go to this page and they appear after refresh the page for one time
![image](https://cloud.githubusercontent.com/assets/22200814/19323101/74bbc0da-9070-11e6-9d45-7e727ecaf58d.png)

05 Related thought
case: make synonyms from different categories
we have categories like the following:
coloration: rose, red, black, white, green, yellow, purple
red: pink, dark red
we need to make “pink” and “rose” as synonym relation, how can we do this?

Solution 1:
remove “rose” from the coloration 
add “rose” to red
make synonyms

Solution 2:
add “pink” as preferred term
add “rose” as “pink”’s synonym

Solution3:
give a view to show coloration and red together
drag the “rose” to “red”
make synonyms

**Comment by rodenhausen** [comment]
1) Comment "make synonyms view". Use new cell drop instead. 
2) Alert user when using a synonym term about the preferred term in place. Offer to execute the action using the preferred term instead.

**Comment by rodenhausen** [comment]
4) Selection view of which relations to re-attach
