### ISSUE TITLE
[Ontology Building] Do part_of relations removing really work? 

### ISSUE THREAD

**Issue by CathyYujie** [biosemantics/etc-site#598]
![image](https://cloud.githubusercontent.com/assets/22200814/20413103/3c741e0e-ace8-11e6-9b58-f8d6e3d3508a.png)
![image](https://cloud.githubusercontent.com/assets/22200814/20413135/63221a24-ace8-11e6-9e4a-b919150fb5e7.png)

Operations:
1) remove the relation:  T01 part_of T
2) add the T01 as a parent term in the part_of grid
it will hint: T01 is still part of T, could not be added as parent. like the second picture.

**Comment by rodenhausen** [comment]
To reproduce:
Initial condition: t is a subclass of t1 and the t1 is a part of t.
Remove the t1 is a part of t row (Yes)
Add t row again. Add t1 to t's row.

**Comment by rodenhausen** [comment]
fixed
