### ISSUE TITLE
[Ontology Building] Using the 'subclass of character' pattern

### ISSUE THREAD

**Issue by CathyYujie** [biosemantics/etc-site#602]
![image](https://cloud.githubusercontent.com/assets/22200814/20414217/935ecb82-acee-11e6-9e35-373fecdefb72.png)

Operations:
1) click on one term in 'architecture'
2) choose the pathpattern: subclass of character
result:
1) add a new category 'character' behind 'Thing' in the tree view
2) 'architecture' become a blank category in 'character' and 'quality' in the tree view
but in the grid view, it still shows the 'architecture' category is not a blank category.

**Comment by rodenhausen** [comment]
This is actually a feature not a bug. We do not want to populate the tree in multiple locations with redundant information. In this case the architecture node below quality and character would have the same content. You should be able to double click the node to re-root the tree view at architecture to see the content in the tree.

It would, however be nice to have a different icon type that separates an empty node from a node where this is the case.
