### ISSUE TITLE
[Ontology Building] Failed to save ontology

### ISSUE THREAD

**Issue by CathyYujie** [biosemantics/etc-site#603]
![image](https://cloud.githubusercontent.com/assets/22200814/20449826/086bde32-ada9-11e6-9d07-5d06a15f5ccc.png)

![image](https://cloud.githubusercontent.com/assets/22200814/20449806/e4b68672-ada8-11e6-8f75-5b78612bd935.png)

I can't save the rubus ontology.
When I click on the button 'save ontology to file manager', it will return a hover says: failed to save ontology.

**Comment by rodenhausen** [comment]
This was probably during a down-time.

**Comment by CathyYujie** [comment]
I still can not save the ontology. 
have tried around 20 times.

the task is the 'steven-rubus-reduced' ontology building task like the following:
![image](https://cloud.githubusercontent.com/assets/22200814/20552014/a3c2cffa-b103-11e6-9303-87751d168724.png)

![image](https://cloud.githubusercontent.com/assets/22200814/20552155/48fc2998-b105-11e6-8ff0-c49d04376d15.png)

Can you check this ontology for me?
