### ISSUE TITLE
[Matrix Generation]Failed to generate matrix.

### ISSUE THREAD

**Issue by CathyYujie** [biosemantics/etc-site#606]
I have three groups of taxon files obtained from text capture task:
1) FNA rubus
2) GC rubus
3) Weakley rubus

Problem:  the Weakley rubus files can not be generated as matrix successfully using the 'steven_rubus_ontology_reduced' ontology.
![image](https://cloud.githubusercontent.com/assets/22200814/21071886/88868328-be6c-11e6-97f2-a13a4af466c4.png)
The other two groups can generate matrix successfully.
And the Weakley rubus files can generate matrix without choosing ontology besides 'Plant'.

I have shared all the related tasks with you.

Can you help me to figure out what's wrong with this Weakley file or the "rubus" ontology?

**Comment by rodenhausen** [comment]
Try again as follows:
(1) Return to the ontology building task 'steven_rubus_ontology_reduced' and save it again. Remember the new folder it is saved to.
(2) Start the matrix generation again for the Weakley rubus files providing the newly saved ontology folder from (1)

There was nothing wrong with the ontology, there was a bug.
