### ISSUE TITLE
[Matrix Generation] Content between "&lt" and "&gt" in description are missing in matrix generation

### ISSUE THREAD

**Issue by CathyYujie** [biosemantics/etc-site#611]
in the description resource:
![image](https://cloud.githubusercontent.com/assets/22200814/21820005/4646fd30-d72b-11e6-95ee-cfc74381e7b9.png)

in the matrix generation system:
![image](https://cloud.githubusercontent.com/assets/22200814/21819955/0baf376e-d72b-11e6-8671-7d0013b23568.png)

Problem:
the content between "&lt" and "&gt" are missing.

-----
the whole description:

<?xml version="1.0" encoding="UTF-8"?>
<bio:treatment xmlns:bio="http://www.github.com/biosemantics" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.github.com/biosemantics https://raw.githubusercontent.com/biosemantics/schemas/master/semanticMarkupInput.xsd">
  <meta>
    <source>
      <author>weakley</author>
      <date>2016</date>
      <title>weakleys key</title>
    </source>
    <processed_by>
      <processor>
        <date>Thursday, November 17, 2016</date>
        <software type="Text Capture Input Generator" version="1.0" />
        <operator>key-gatherer</operator>
      </processor>
    </processed_by>
  </meta>
  <taxon_identification status="ACCEPTED">
    <taxon_name rank="species" authority="weakley" date="2016">R._pubescens</taxon_name>
  </taxon_identification>
  <description type="morphology">Leaves 3-9-foliolate (reduced simple leaves may also be present in the inflorescence). Upright stems herbaceous, annual, not differentiated into primocanes and floricanes, unarmed or with a few weak bristles; stipules oblanceolate; [e. WV northward]; [subgenus Cylactis – dwarf raspberries]</description>
  <description type="morphology">Herbs or subshrubs (if woody at base, then &lt; 3 dm tall). Leaves compound (at least the lower and better developed). Leaves 1-compound, either simply pinnately compound or simply palmately compound,. Principal (basal-most) leaves palmately compound, with 3-7 (-9) leaflets. Principal leaves distinctly petiolate, the petiole often longer than the leaflets, 3-7 (-9)-foliolate; fruit of achenes; leaves basal and cauline. Principal leaves 3-foliolate. Plants in flower. Petals white (or slightly pinkish). Calyx lobes not subtended by bractlets; [tribe Rubeae]. Herbs or subshrubs (if woody at base, then &lt; 3 dm tall). Leaves compound (at least the lower and better developed). Leaves 1-compound, either simply pinnately compound or simply palmately compound,. Principal (basal-most) leaves palmately compound, with 3-7 (-9) leaflets. Principal leaves distinctly petiolate, the petiole often longer than the leaflets, 3-7 (-9)-foliolate; fruit of achenes; leaves basal and cauline. Principal leaves 3-foliolate. Plants in fruit (or sterile). Leaflets evenly serrate or crenate, each well-developed leaflet with &gt; 7 teeth. Calyx lobes not subtended by bractlets. Fruit an aggregate of fleshy, adherent drupelets; leaflets acuminate at apex; [tribe Rubeae]</description>
</bio:treatment>

**Comment by rodenhausen** [comment]
This problem stems from sentence extraction in the perl portion of charaparser. The sentences read at the location below from the table populated by the perl portion lacks the part of the sentence between the < and > part of the sentence.

**Comment by rodenhausen** [comment]
Problem does not appear in the perl portion in a windows environment. Needs debugging in linux environment.

**Comment by rodenhausen** [comment]
Problem also does not appear debugging in my linux environment. On the server however it can be reproduced.

**Comment by rodenhausen** [comment]
tested that perl and mysql version do not play a role.

**Comment by rodenhausen** [comment]
fix: https://github.com/biosemantics/charaparser/commit/d29abd1eb0559bfe050ccc4aed648cb90160caba
