### ISSUE TITLE
[Matrix Generation] Unexpected "Synonym-root" appears in matrix generation results

### ISSUE THREAD

**Issue by CathyYujie** [biosemantics/etc-site#613]
When use the ontology to change some term in matrix generation, such as
         turn "infl" to "inflorescence"
in the context:
![image](https://cloud.githubusercontent.com/assets/22200814/21869156/65b5ef12-d813-11e6-881a-1919b314f629.png)
in the matrix generation output:
![image](https://cloud.githubusercontent.com/assets/22200814/21869199/a756430e-d813-11e6-9eee-ea2e3d79c7b2.png)
in the taxon comparison:
![image](https://cloud.githubusercontent.com/assets/22200814/21869211/b87b391e-d813-11e6-928f-d8fbc85f9270.png)

it will be more reasonable to change the "Synonym-root architecture racemiform" to "inflorescence architecture racemiform"

**Comment by CathyYujie** [comment]
It still appears in the interfaces of matrix generation, ontology and taxon comparison like the following picture:
![image](https://cloud.githubusercontent.com/assets/22200814/23088264/1ff4024c-f538-11e6-9ad9-f56741281953.png)
![image](https://cloud.githubusercontent.com/assets/22200814/23088270/2cc8bc60-f538-11e6-99c9-b27931796d72.png)
![image](https://cloud.githubusercontent.com/assets/22200814/23088298/7d8d57f0-f538-11e6-93f4-854c235037b0.png)

It should not replace the parent word.
For example, leaf is the parent word of leaves. The structure word will be leaf instead of synonym-root.

**Comment by rodenhausen** [comment]
Did you recreate the ontology or did you use the old one?

**Comment by CathyYujie** [comment]
Yes, the problem does not exist with the new saved ontology.

I saved the rubus-ontology again, ran the matrix generation procedures of the three taxons and compared them in taxon comparison, the "synonym-root" did not appear ^^
