### ISSUE TITLE
[Ontology Building] Preferred term doesn't replace the synonym term after making synonyms 

### ISSUE THREAD

**Issue by CathyYujie** [biosemantics/etc-site#616]
Problem:
Terms do not appear after making synonyms.
The preferred term doesn't appear while the synonym disappears.

processes:
1) add the "purple-black" as subclass of purple
![image](https://cloud.githubusercontent.com/assets/22200814/24482259/cc5207b0-14a4-11e7-8721-31cd6cee30b2.png)

2) make "purple-black" ad synonym of preferred term "purple black"
![image](https://cloud.githubusercontent.com/assets/22200814/24482303/0aa779a0-14a5-11e7-9d5f-be96170a96ae.png)

3) in the category relation, "purple-black" disappears and "purple black" doesn't appear
refresh the page, the two terms still do not appear
![image](https://cloud.githubusercontent.com/assets/22200814/24482313/1a89b9c8-14a5-11e7-80c9-3778b9236c03.png)

**Comment by danveno** [comment]
This problem has been fixed. But should the user at least select one relation?

**Comment by danveno** [comment]
add a tip to show users that if selecting multiple relations, press Ctrl in the keyboard.

**Comment by danveno** [comment]
CreateRelationEvents shoud be executed first to prevent duplicate relations.
Fixed.
