### ISSUE TITLE
[Ontology Building] Just create a new term when drag the folder title to the create area

### ISSUE THREAD

**Issue by CathyYujie** [biosemantics/etc-site#617]
The problem is
it is hard for users to understand the result of dragging the title of the folder to the  create area.
The result is the system will create all the terms in the folder to be superclasses/parents/preferred terms in the grid except the folder title.

Advice:
please adjust the result as just creating the folder title to be a new superclass/parent/preferred term when dragging the folder into the yellow create area.

![image](https://cloud.githubusercontent.com/assets/22200814/24732464/f4ef4a4e-1a25-11e7-8c47-7f1a507d307c.png)

**Comment by danveno** [comment]
fixed
