### ISSUE TITLE
[Ontology Building] The description information of the pattern function needs to be adjusted

### ISSUE THREAD

**Issue by CathyYujie** [biosemantics/etc-site#618]
1. The information in the brackets needs to be adjusted to "recommended relations".
![image](https://cloud.githubusercontent.com/assets/22200814/24732635/fcd0c660-1a26-11e7-9243-40dbbcb894eb.png)

2. The description in the hover needs to be adjusted to "Recommendations"
![image](https://cloud.githubusercontent.com/assets/22200814/24732754/bc80247e-1a27-11e7-8ef3-f1267eaf715c.png)

3. Replace the sentence to be the title of the window in the following.
![image](https://cloud.githubusercontent.com/assets/22200814/24732778/ef1fdc1c-1a27-11e7-9eac-3d8f083f68f3.png)

**Comment by danveno** [comment]
For the second one, it seems to be more appropriate to use "Show recommended relations" as the title of the dialogue.


Fixed but not deployed yet
