### ISSUE TITLE
[Ontology building] “out of sync”when import synonym relationship after removing

### ISSUE THREAD

**Issue by CathyYujie** [biosemantics/etc-site#619]
Steps:
1. add synonym relationship through dragging, ex, B synonym of A
2. remove this row
3. import: A, B and click"OK"
4. prompt like the following:
![image](https://cloud.githubusercontent.com/assets/22200814/25147166/68fb1a58-242b-11e7-82a9-3e9eaf627674.png)

Other attempts without this prompt
1. drag terms to be synonyms, remove, drag the same relationship to build synonyms again——no "out of sync" prompt
2. select recommended relationships to be synonyms, remove, import the same relationship to build synonyms again——no "out of sync" prompt
3. import, remove, import again——no "out of sync" prompt

**Comment by danveno** [comment]
This is about import transactions. There are some problems there:
1, the input text should be validated first;
2, every relation should be validate.
