### ISSUE TITLE
[ontology building] Terms will not be replaced by preferred term when import synonym relationships

### ISSUE THREAD

**Issue by CathyYujie** [biosemantics/etc-site#620]
Steps:
1. make "yellow-green is_a a"
2. import "yellow green, yellow-green" to be synonyms
no pop-up window offering choice whether to replace the term
3. synonym relationship "yellow-green synonym of yellow green" will be built successfully, but the term yellow-green in is_a relationship"a, yellow-green" will not be replaced as "a, yellow green"

![image](https://cloud.githubusercontent.com/assets/22200814/25150273/3b1f5896-2436-11e7-838a-a2806a3039fa.png)

![image](https://cloud.githubusercontent.com/assets/22200814/25150425/b5667aee-2436-11e7-8fc7-0591f1b20b8b.png)

Notes: Make synonyms through dragging and selecting recommended relationships will invoke the replace window.

**Comment by danveno** [comment]
we leave it for users
