### ISSUE TITLE
[ontology building] out of sync when input nothing in the import window

### ISSUE THREAD

**Issue by CathyYujie** [biosemantics/etc-site#621]
![image](https://cloud.githubusercontent.com/assets/22200814/25151637/2326c8c8-243b-11e7-931c-955e739adb33.png)

![image](https://cloud.githubusercontent.com/assets/22200814/25151622/11a5a678-243b-11e7-885c-0daf6956c46a.png)

**Comment by danveno** [comment]
it's not out of sync, just an alert

**Comment by danveno** [comment]
but the import should be validated before sending to the server.
