### ISSUE TITLE
[Ontology Building] Keep the instructions appearing in the non-specific window

### ISSUE THREAD

**Issue by CathyYujie** [biosemantics/etc-site#624]
![image](https://cloud.githubusercontent.com/assets/22200814/25253530/2087de62-25d6-11e7-8bb2-0ebbae02a716.png)

**Comment by danveno** [comment]
Now, the appearance looks like:
![image](https://cloud.githubusercontent.com/assets/5811267/25256174/aea6a6bc-25e3-11e7-81b6-fbbb168cb64c.png)
