### ISSUE TITLE
[Ontology Building] Pattern: Non-specific material anatomical entity pattern

### ISSUE THREAD

**Issue by CathyYujie** [biosemantics/etc-site#625]
一、需要增加part_of关系推荐
![image](https://cloud.githubusercontent.com/assets/22200814/25255952/821b6408-25e2-11e7-93bd-979504a88962.png)

二、需要解决以下逻辑问题：

1) 没有 non-specific pattern

手动添加关系
-base part of blade
-base part of leaflet

触发四种关系
-blade base part of blade
-leaflet base part of leaflet
-blade base subclass of base
-leaflet base subclass of base

但，pattern中不推荐 base subclass of non specific anatomical entity

2) out of sync
如果base, blade base或leaflet base已存在于除part of之外任何关系中（如base subclass of material anatomical entity或foliage synonym of base），则

-报out of sync
-确认后 pattern窗口中推荐 base subclass of non specific anatomical entity
-四种关系没有被触发

**Comment by danveno** [comment]
I will split this into multiple issues.
