### ISSUE TITLE
[Ontology building] comment out the default relations temporarily

### ISSUE THREAD

**Issue by CathyYujie** [biosemantics/etc-site#631]
![image](https://cloud.githubusercontent.com/assets/22200814/25637021/3f75b932-2f38-11e7-94a0-82b4f087083c.png)

**Comment by danveno** [comment]
There are two scenarios. One is clearing and another is initialization. Should these relations be kept when initializing the ontology? 

When clearing the relations, should all be removed?

**Comment by CathyYujie** [comment]
1）initialization
When create a new ontology building task, initialize the two is_a relations:
-quality
-material anatomical entity, non-specific material anatomical entity

2)clearing
After use the function of "clear"
Remove all the relations except the two initialized is_a relations:
-quality
-material anatomical entity, non-specific material anatomical entity

**The default relations which should be commented out are:**
1) all the relations related to modifiers
a. modifier categories
![image](https://cloud.githubusercontent.com/assets/22200814/25644021/036f58ba-2f58-11e7-9f38-1c1ec0cb16f2.png)
![image](https://cloud.githubusercontent.com/assets/22200814/25644122/82a90158-2f58-11e7-9066-720df71d7b89.png)
b. modifier synonyms
![image](https://cloud.githubusercontent.com/assets/22200814/25644039/1e703544-2f58-11e7-9888-abccc17dd644.png)

2) the relations generated automatically
![image](https://cloud.githubusercontent.com/assets/22200814/25644114/77a6e90a-2f58-11e7-8749-0440a1364c50.png)
![image](https://cloud.githubusercontent.com/assets/22200814/25644174/e1d4917e-2f58-11e7-988d-aeee3e0e9ab8.png)

**Comment by danveno** [comment]
I think it's better to keep all those relations when setting up a new ontology, and only keep the necessary ones after triggering Clear function.
