### ISSUE TITLE
[Ontology Building] Change the conditions to trigger non-specific material anatomical entity pattern

### ISSUE THREAD

**Issue by CathyYujie** [biosemantics/etc-site#635]
for example:
leaflet
base
leaflet base

when leaflet and base are in the folder or subfolder of material anatomical entity in the candidate list, give the recommended relations to leaflet base:
leaflet base part of leaflet
base subclass of non-specific material anatomical entity

instead of making subclass_of relations between leaflet, base and material anatomical entity

**Comment by danveno** [comment]
The terms could be under the folder of the material anatomical entity or an offspring of the material anatomical entity.
