### ISSUE TITLE
[UI] etc-dev select a file 

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#638]
see https://www.screencast.com/t/va0Je6KFsEx

Basically when you have a long list of files in the File Manager, and you are trying to select one file for deletion, you click on the file and the interface refreshes and the file selected is no longer in your view. 

etc and etc-dev share the same issue.

**Comment by danveno** [comment]
This seems to be a bug in the Tree widget. Possibly related to https://github.com/gwtproject/gwt/issues/9475.

**Comment by danveno** [comment]
A browser  event is added to the FileTree when initializing the tree:
@Override
			 public void onBrowserEvent(Event event) {
			        if (DOM.eventGetType(event) == Event.ONMOUSEDOWN) {
			        	super.onClick(event);
			        	TreeNode<FileTreeItem> node = findNode(event.getEventTarget().<Element> cast());
					        if(!(node.getModel() instanceof FolderTreeItem)) {
						      this.scrollIntoView(node.getModel());
					        }
			        }

			        super.onBrowserEvent(event);
			 }
