### ISSUE TITLE
[Matrix Review] values not highlighted in context

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#639]
See https://www.screencast.com/t/b4MtFpAtIA
A value 99.9 extracted as ph maximum for Toxopsis Calypsus is not highlighted in the " context" (its source file).

I attached the input file so you can regenerate 
[MicroPIE_Input_Samples.txt](https://github.com/biosemantics/etc-site/files/1089232/MicroPIE_Input_Samples.txt)
this issue.

**Comment by danveno** [comment]
I tried not to highlight the value only by simple matching but word matching. 
The RegExp is updated.
