### ISSUE TITLE
Matrix Generation: Multiple taxon names at different ranks doesn't appear on matrix

### ISSUE THREAD

**Issue by elviscat** [biosemantics/etc-site#90]
If we have the following input (in batch format):
=>
=>
author: Kelly M and Samaaai T
year: 2002
title: Systema Porifera
DOI:10.1007/978-1-4615-0747-5_1
full citation: Kelly M, Samaaai T. 2002. Suborder Latrunculina subord. nov. incertae sedis. In: Hooper JNA and Van Soest RWM, editors. Systema Porifera. A guide to the classification of sponges. New York: Kluwer Academic/Plenum Publishers. p. 707.
suborder name: Latrunculina subord. nov. incertae sedis
family name: Aus Wu, 2014
morphology: "Poecilosclerida incertae sedis with acanthodiscorhabds forming and ectosomal skelton; without chelae or sigma microscleres."

We should have the following output in "name" column:
Suborder=Latrunculina:FAMILY=Aus::author=Kelly M and Samaaai T,date=2002

But the current output is:
FAMILY=Aus:author=Kelly M and Samaaai T,date=2002

**Comment by rodenhausen** [comment]
fixed duplicate: https://github.com/biosemantics/etc-site/issues/248 f
